development:
  adapter: postgresql
  encoding: unicode
  database: subway_alert_development
  pool: 5
  host: localhost
  username: larrybuch
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: subway_alert_production
  pool: 5
  host: localhost
  username: larrybuch
  password: